version: '3.2'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: novita_diamonds_nginx
    volumes:
      - ./:/home/app/app
    restart: always
    networks:
      - build_network
    ports:
      - '80:81'
      - '443:443'
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: novita_diamonds_php
    volumes:
      - ./:/home/app/app
    restart: always
    networks:
      - build_network
  db:
    container_name: novita_diamonds_db
    volumes:
      - ./:/home/app/app/db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - build_network
networks:
  build_network:
    external: true